# @format

name: Flutter_Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Install and set Flutter version
        uses: subosito/flutter-action@v1.4.0
        with:
          flutter-version: "1.22.0"

      - name: create env file
        run: touch .env

      - name: Restore packages
        run: flutter pub get

      - name: Analyze
        run: flutter analyze

      - name: Run tests
        run: flutter test --coverage

      - name: Upload coverage to codecov
        run: bash <(curl -s https://codecov.io/bash) -t $CODECOV_TOKEN
        shell: bash
